version: "3.3"
services:
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: ./server/
      dockerfile: Dockerfile

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "80:80"
