name: Deploy (Client App)

on:
  workflow_run:
    workflows: 
    - "Build (Client)"
    types:
    - completed
    push:
      paths:
      - 'client/**'
      branches: [ main ]
  
jobs:
  deploy:
    name: Deploy Client App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build React App
      run: |
        yarn install
        yarn build

    - name: Deploy to S3 and Invalidate Cloudfront
      id: deploy-s3
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
      run: |
        aws s3 sync ./build $AWS_S3_BUCKET --delete
        aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
